question_data = [{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "George Lucas directed the entire original Star Wars trilogy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
